all = {
  'EDB': ['SR', 'CS', 'GR', 'XC'],
  'GLC': ['SR', 'CS', 'GR', 'VT'],
  'GLQ': ['ALL'],
  'ABD': ['ALL'],
  'INV': ['ALL'],
  'BHM': ['VT', 'XC'],
  'EUS': ['VT', 'CS'],
  'CDF': ['AW'],
  'KGX': ['GR'],
  'MCV': ['TP'],
  'LIV': ['NT'],
  'MAN': ['NT'],
  'WGW': ['NT'],
  'YRK': ['TP'],
  'BRI': ['GW'],
  'BRI': ['GW'],
  'SAL': ['SW'],
  'WAT': ['ALL']
}